import { StyleSheet } from 'react-native';

export const baseStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F5F7FB' },
  container: { padding: 20, paddingBottom: 36 },
  header: { marginBottom: 20 },
  kicker: { color: '#B54708', fontSize: 14, fontWeight: '800', marginBottom: 6, textTransform: 'uppercase' },
  title: { color: '#101828', fontSize: 28, fontWeight: '800', lineHeight: 34 },
  subtitle: { color: '#667085', fontSize: 15, lineHeight: 22, marginTop: 8 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  sectionTitle: { color: '#101828', fontSize: 20, fontWeight: '800' },
  sectionCount: { color: '#00684F', fontSize: 15, fontWeight: '800' },
  error: { color: '#B42318', fontSize: 13, fontWeight: '800', marginBottom: 12 },
  todoList: { gap: 10 },
  empty: { color: '#667085', fontSize: 14, lineHeight: 20 },
  todoCard: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, padding: 14 },
  todoTopRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  checkbox: { alignItems: 'center', backgroundColor: '#D0D5DD', borderRadius: 8, height: 32, justifyContent: 'center', width: 32 },
  disabledAction: { opacity: 0.5 },
  syncDot: { borderRadius: 5, height: 10, marginTop: 3, width: 10 },
  syncDotDone: { backgroundColor: '#12B76A' },
  syncDotPending: { backgroundColor: '#D92D20' },
  todoTitleBlock: { flex: 1 },
  todoTitle: { color: '#101828', fontSize: 16, fontWeight: '800' },
  todoMeta: { color: '#667085', fontSize: 12, lineHeight: 18, marginTop: 3 },
  expandButton: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },
  todoDetails: { borderTopColor: '#EAECF0', borderTopWidth: 1, gap: 8, marginTop: 12, paddingTop: 12 },
  todoDescription: { color: '#475467', fontSize: 13, lineHeight: 19 },
  subtaskRow: { alignItems: 'center', flexDirection: 'row', gap: 9, minHeight: 34 },
  subtaskCheckbox: { alignItems: 'center', borderColor: '#D0D5DD', borderRadius: 7, borderWidth: 1, height: 24, justifyContent: 'center', width: 24 },
  subtaskCheckboxDone: { backgroundColor: '#047857', borderColor: '#047857' },
  subtaskText: { color: '#344054', flex: 1, fontSize: 14, fontWeight: '700' },
  subtaskTextDone: { color: '#98A2B3', textDecorationLine: 'line-through' },
  historySection: { marginTop: 24 },
  historyCard: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, padding: 14 },
  historySubtasks: { gap: 4, marginTop: 10 },
  historySubtask: { color: '#667085', fontSize: 12, lineHeight: 18 },
  notesPanel: { marginBottom: 18 },
  notesContent: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, gap: 10, padding: 12 },
  noteCard: { backgroundColor: '#F9FAFB', borderColor: '#EAECF0', borderRadius: 8, borderWidth: 1, padding: 12 },
  noteCardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  noteCategory: { color: '#00684F', fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  noteBadge: { color: '#047857', fontSize: 12, fontWeight: '800' },
  noteTitle: { color: '#101828', fontSize: 16, fontWeight: '800', marginTop: 7 },
  noteText: { color: '#344054', fontSize: 14, lineHeight: 20, marginTop: 5 },
  addPanel: { marginTop: 18 },
  addHeader: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 14 },
  headerTextBlock: { flex: 1, paddingRight: 10 },
  chevronIcon: { flexShrink: 0, textAlign: 'center', width: 28 },
  chevronIconSmall: { flexShrink: 0, textAlign: 'center', width: 22 },
  addTitle: { color: '#101828', fontSize: 17, fontWeight: '800' },
  addHint: { color: '#667085', fontSize: 13, lineHeight: 19, marginTop: 3, paddingRight: 8 },
  form: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, gap: 10, padding: 14 },
  input: { backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, color: '#101828', fontSize: 15, minHeight: 46, paddingHorizontal: 12, paddingVertical: 10 },
  textArea: { minHeight: 86, textAlignVertical: 'top' },
  fieldLabel: { color: '#344054', fontSize: 13, fontWeight: '800' },
  subtaskInputRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  subtaskInput: { flex: 1 },
  removeButton: { alignItems: 'center', backgroundColor: '#FEF3F2', borderColor: '#FECDCA', borderRadius: 8, borderWidth: 1, height: 46, justifyContent: 'center', width: 46 },
  removeButtonDisabled: { opacity: 0.4 },
  secondaryButton: { alignItems: 'center', backgroundColor: '#E7F4EF', borderColor: '#93D3BA', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: 44 },
  secondaryButtonText: { color: '#00684F', fontSize: 14, fontWeight: '800' },
  button: { alignItems: 'center', backgroundColor: '#00684F', borderRadius: 8, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 48 },
  buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
});
