import { StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const baseStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F3F7F4' },
  container: { paddingBottom: 40 },
  hero: {
    backgroundColor: '#0F3D32',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  heroGlowLarge: {
    backgroundColor: '#1E6F57',
    borderRadius: 140,
    height: 220,
    opacity: 0.26,
    position: 'absolute',
    right: -50,
    top: -70,
    width: 220,
  },
  heroGlowSmall: {
    backgroundColor: '#BDEBD6',
    borderRadius: 100,
    height: 150,
    left: -48,
    opacity: 0.18,
    position: 'absolute',
    top: 18,
    width: 150,
  },
  heroKicker: {
    color: '#D6F5E6',
    fontFamily: Fonts.rounded,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#FFFFFF',
    fontFamily: Fonts.serif,
    fontSize: 30,
    lineHeight: 34,
    marginTop: 10,
  },
  heroSubtitle: {
    color: '#D1FADF',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
    maxWidth: 560,
  },
  heroMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 18 },
  heroPill: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  heroPillText: { color: '#ECFDF3', fontSize: 12, fontWeight: '700' },
  content: { gap: 18, paddingHorizontal: 18, paddingTop: 18 },
  card: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E3DC',
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    shadowColor: '#102A22',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 24,
  },
  cardMuted: {
    backgroundColor: '#F7FBF8',
    borderColor: '#DDE9E1',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, marginBottom: 12 },
  sectionTitle: { color: '#16322A', fontFamily: Fonts.serif, fontSize: 24 },
  sectionMeta: { color: '#4D6B61', fontSize: 13, fontWeight: '700' },
  segmentRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  segmentButton: {
    backgroundColor: '#EEF5F0',
    borderColor: '#D6E3DB',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  segmentButtonActive: {
    backgroundColor: '#163F34',
    borderColor: '#163F34',
  },
  segmentText: { color: '#33584B', fontSize: 14, fontWeight: '800' },
  segmentTextActive: { color: '#FFFFFF' },
  filterScroll: { marginTop: 2 },
  filterRow: { flexDirection: 'row', gap: 8, paddingRight: 18 },
  chip: {
    backgroundColor: '#F7FBF8',
    borderColor: '#D8E5DD',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  chipActive: {
    backgroundColor: '#DFF3E8',
    borderColor: '#51A57E',
  },
  chipText: { color: '#33584B', fontSize: 13, fontWeight: '700' },
  chipTextActive: { color: '#0D5C3D' },
  searchBox: {
    alignItems: 'center',
    backgroundColor: '#F7FBF8',
    borderColor: '#D7E3DC',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  searchInput: {
    color: '#102A22',
    flex: 1,
    fontSize: 15,
    minHeight: 46,
    paddingVertical: 10,
  },
  sectionText: { color: '#577468', fontSize: 14, lineHeight: 21 },
  semesterGrid: { gap: 14 },
  semesterCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D9E6DE',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
  },
  semesterBand: { height: 8 },
  semesterBody: { padding: 16 },
  semesterTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  semesterLabel: { color: '#18352C', fontFamily: Fonts.serif, fontSize: 22 },
  semesterSub: { color: '#608175', fontSize: 13, marginTop: 4 },
  semesterCredits: { color: '#0B6B49', fontSize: 24, fontWeight: '800' },
  semesterCreditsLabel: { color: '#608175', fontSize: 11, fontWeight: '700', textAlign: 'right', textTransform: 'uppercase' },
  moduleStack: { gap: 10, marginTop: 16 },
  moduleTile: {
    backgroundColor: '#F8FBF9',
    borderColor: '#DDE8E1',
    borderRadius: 16,
    borderWidth: 1,
    padding: 13,
  },
  moduleTileHighlight: {
    backgroundColor: '#ECF9F2',
    borderColor: '#72BF98',
  },
  moduleTileTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  moduleTitle: { color: '#163229', flex: 1, fontSize: 15, fontWeight: '800', lineHeight: 20 },
  moduleCredits: { color: '#0F6C4A', fontSize: 12, fontWeight: '800' },
  moduleMeta: { color: '#638174', fontSize: 12, lineHeight: 18, marginTop: 6 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  miniTag: {
    backgroundColor: '#EAF5EE',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  miniTagText: { color: '#2A644E', fontSize: 11, fontWeight: '700' },
  slotTile: {
    backgroundColor: '#FFF8EC',
    borderColor: '#F4D39A',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    padding: 13,
  },
  slotTitle: { color: '#7C4D00', fontSize: 14, fontWeight: '800' },
  slotMeta: { color: '#A15C00', fontSize: 12, lineHeight: 18, marginTop: 4 },
  slotCandidateWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  slotCandidateChip: {
    backgroundColor: '#FFFFFF',
    borderColor: '#F1C56F',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  slotCandidateText: { color: '#8C5A00', fontSize: 12, fontWeight: '700' },
  emptyState: { color: '#71897F', fontSize: 14, lineHeight: 21 },
  graphToolbar: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 12 },
  graphSummary: { color: '#5E7C70', fontSize: 13, lineHeight: 19, marginTop: 12 },
  graphShell: {
    backgroundColor: '#F4FAF6',
    borderColor: '#D8E5DD',
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 14,
    overflow: 'hidden',
  },
  graphViewport: { height: 560 },
  graphControls: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end', padding: 12 },
  graphButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CBDAD1',
    borderRadius: 12,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    minWidth: 38,
    paddingHorizontal: 12,
  },
  graphButtonText: { color: '#244A3D', fontSize: 14, fontWeight: '800' },
  loadingBlock: { alignItems: 'center', gap: 10, paddingVertical: 50 },
  loadingText: { color: '#55756A', fontSize: 14, fontWeight: '700' },
  errorCard: {
    backgroundColor: '#FFF3F2',
    borderColor: '#F4C7C3',
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  errorTitle: { color: '#B42318', fontSize: 15, fontWeight: '800' },
  errorText: { color: '#9E3C33', fontSize: 13, lineHeight: 19, marginTop: 6 },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(12, 24, 20, 0.52)',
    flex: 1,
    justifyContent: 'flex-end',
    padding: 12,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '88%',
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 24,
    width: '100%',
  },
  modalHandle: {
    alignSelf: 'center',
    backgroundColor: '#D0DDD5',
    borderRadius: 999,
    height: 5,
    marginBottom: 14,
    width: 58,
  },
  modalTitle: { color: '#163229', fontFamily: Fonts.serif, fontSize: 28, lineHeight: 32 },
  modalSubtitle: { color: '#5D7D70', fontSize: 14, lineHeight: 20, marginTop: 8 },
  modalBlock: { marginTop: 18 },
  modalBlockTitle: { color: '#17332A', fontSize: 13, fontWeight: '800', letterSpacing: 0.8, textTransform: 'uppercase' },
  modalList: { gap: 8, marginTop: 10 },
  modalItem: { color: '#35584C', fontSize: 14, lineHeight: 21 },
  sourceCard: {
    backgroundColor: '#F8FBF9',
    borderColor: '#DCE8E0',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    padding: 12,
  },
  sourceTitle: { color: '#1E3E33', fontSize: 14, fontWeight: '800' },
  sourceMeta: { color: '#618175', fontSize: 12, lineHeight: 18, marginTop: 4 },
});
