import { StyleSheet } from 'react-native';

export const baseStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F5F7FB' },
  container: { padding: 20, paddingBottom: 36 },
  header: { marginBottom: 20 },
  kicker: { color: '#C11574', fontSize: 14, fontWeight: '800', marginBottom: 6, textTransform: 'uppercase' },
  title: { color: '#101828', fontSize: 28, fontWeight: '800', lineHeight: 34 },
  subtitle: { color: '#667085', fontSize: 15, lineHeight: 22, marginTop: 8 },
  segmentedControl: { backgroundColor: '#E4E7EC', borderRadius: 8, flexDirection: 'row', gap: 4, marginBottom: 14, padding: 4 },
  segmentButton: { alignItems: 'center', borderRadius: 6, flex: 1, justifyContent: 'center', minHeight: 42, paddingHorizontal: 10 },
  segmentButtonActive: { backgroundColor: '#FFFFFF' },
  segmentButtonText: { color: '#667085', fontSize: 14, fontWeight: '800' },
  segmentButtonTextActive: { color: '#00684F' },
  searchBox: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 10, marginBottom: 14, paddingHorizontal: 14 },
  searchInput: { color: '#101828', flex: 1, fontSize: 15, minHeight: 48 },
  form: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, gap: 10, padding: 14 },
  input: { backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, color: '#101828', fontSize: 15, minHeight: 46, paddingHorizontal: 12 },
  button: { alignItems: 'center', backgroundColor: '#00684F', borderRadius: 8, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 48 },
  buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  error: { color: '#B42318', fontSize: 13, fontWeight: '700' },
  empty: { color: '#667085', fontSize: 14, lineHeight: 20 },
  contactList: { gap: 12, marginBottom: 18 },
  contactCard: { alignItems: 'flex-start', backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 12, padding: 14 },
  avatar: { alignItems: 'center', backgroundColor: '#FCE7F3', borderRadius: 8, height: 44, justifyContent: 'center', width: 44 },
  avatarText: { color: '#C11574', fontSize: 14, fontWeight: '800' },
  hfuAvatar: { alignItems: 'center', backgroundColor: '#DCFCE7', borderRadius: 8, height: 44, justifyContent: 'center', width: 44 },
  hfuAvatarText: { color: '#00684F', fontSize: 14, fontWeight: '800' },
  contactContent: { flex: 1 },
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  contactName: { color: '#101828', flex: 1, fontSize: 17, fontWeight: '800' },
  syncDot: { borderRadius: 5, height: 10, marginTop: 5, width: 10 },
  syncDotDone: { backgroundColor: '#12B76A' },
  syncDotPending: { backgroundColor: '#D92D20' },
  personalBadge: { color: '#047857', fontSize: 12, fontWeight: '800' },
  contactRole: { color: '#475467', fontSize: 14, fontWeight: '700', marginTop: 3 },
  contactDetail: { color: '#667085', fontSize: 13, lineHeight: 19, marginTop: 5 },
  addPanel: { marginTop: 4 },
  addHeader: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 14 },
  headerTextBlock: { flex: 1, paddingRight: 10 },
  chevronIcon: { flexShrink: 0, textAlign: 'center', width: 28 },
  addTitle: { color: '#101828', fontSize: 17, fontWeight: '800' },
  addHint: { color: '#667085', fontSize: 13, lineHeight: 19, marginTop: 3, paddingRight: 8 },
  hfuHeader: { marginBottom: 14 },
  sectionTitle: { color: '#101828', fontSize: 22, fontWeight: '800', lineHeight: 28 },
  sectionSubtitle: { color: '#667085', fontSize: 14, lineHeight: 21, marginTop: 5 },
  filterPanel: { gap: 12, marginBottom: 14 },
  filterGroup: { gap: 8 },
  filterGroupTitle: { color: '#475467', fontSize: 13, fontWeight: '800' },
  filterChips: { flexDirection: 'row', gap: 8, paddingRight: 20 },
  filterChip: { backgroundColor: '#FFFFFF', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 38, paddingHorizontal: 12 },
  filterChipActive: { backgroundColor: '#E6F4EF', borderColor: '#00684F' },
  filterChipText: { color: '#475467', fontSize: 13, fontWeight: '700' },
  filterChipTextActive: { color: '#00684F' },
  hfuDetails: { borderTopColor: '#E4E7EC', borderTopWidth: 1, marginTop: 10, paddingTop: 8 },
  linkButton: { alignItems: 'center', flexDirection: 'row', gap: 6, marginTop: 8, minHeight: 34 },
  linkButtonText: { color: '#00684F', fontSize: 13, fontWeight: '800' },
  loadMoreButton: { alignItems: 'center', backgroundColor: '#E6F4EF', borderColor: '#00684F', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 46, paddingHorizontal: 14 },
  loadMoreButtonDisabled: { opacity: 0.55 },
  loadMoreButtonText: { color: '#00684F', fontSize: 14, fontWeight: '800' },
});
export { contactsBaseStyles as baseStyles } from '@/src/shared/styles/moduleStyles';
