import { StyleSheet } from 'react-native';

const qrSize = 260;

export const baseStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F7FB',
  },
  container: {
    padding: 20,
    paddingBottom: 36,
  },
  header: {
    marginBottom: 20,
  },
  kicker: {
    color: '#00684F',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  title: {
    color: '#101828',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  subtitle: {
    color: '#667085',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  switchRow: {
    backgroundColor: '#EAECF0',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    marginBottom: 14,
    padding: 4,
  },
  switchButton: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 42,
  },
  switchButtonActive: {
    backgroundColor: '#00684F',
  },
  switchText: {
    color: '#475467',
    fontSize: 14,
    fontWeight: '800',
  },
  switchTextActive: {
    color: '#FFFFFF',
  },
  form: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  input: {
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    color: '#101828',
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  comboBox: {
    position: 'relative',
    zIndex: 1,
  },
  comboBoxOpen: {
    elevation: 12,
    zIndex: 1000,
  },
  comboButton: {
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  comboLabel: {
    color: '#101828',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  chevronIcon: { flexShrink: 0, textAlign: 'center', width: 28 },
  comboMenu: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 12,
    marginTop: 6,
    overflow: 'hidden',
    zIndex: 1001,
  },
  comboOption: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  comboOptionActive: {
    backgroundColor: '#E7F4EF',
  },
  comboOptionText: {
    color: '#475467',
    fontSize: 14,
    fontWeight: '800',
  },
  comboOptionTextActive: {
    color: '#00684F',
  },
  roleToggle: {
    flexDirection: 'row',
    gap: 10,
  },
  roleButton: {
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 46,
  },
  roleButtonActive: {
    backgroundColor: '#004B3A',
    borderColor: '#004B3A',
  },
  roleText: {
    color: '#475467',
    fontSize: 14,
    fontWeight: '800',
  },
  roleTextActive: {
    color: '#FFFFFF',
  },
  error: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  success: {
    color: '#047857',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 19,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#00684F',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 50,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  profileCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    padding: 16,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#E7F4EF',
    borderRadius: 8,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  profileContent: {
    flex: 1,
  },
  profileName: {
    color: '#101828',
    fontSize: 18,
    fontWeight: '800',
  },
  profileMeta: {
    color: '#475467',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  profileRole: {
    color: '#00684F',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 19,
    marginTop: 6,
  },
  themeToggle: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
    minHeight: 58,
    paddingHorizontal: 14,
  },
  themeToggleDark: {
    backgroundColor: '#101828',
    borderColor: '#344054',
  },
  themeToggleContent: {
    flex: 1,
  },
  themeToggleTitle: {
    color: '#101828',
    fontSize: 15,
    fontWeight: '800',
  },
  themeToggleTitleDark: {
    color: '#FFFFFF',
  },
  themeToggleMeta: {
    color: '#667085',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  themeToggleMetaDark: {
    color: '#D0D5DD',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#FEF3F2',
    borderColor: '#FECDCA',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
  },
  secondaryButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '800',
  },
  keyTitle: { color: '#101828', fontSize: 16, fontWeight: '800' },
  keyHint: { color: '#667085', fontSize: 13, lineHeight: 19, marginTop: 4 },
  keyInput: { minHeight: 110, textAlignVertical: 'top' },
  keyBox: { backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, gap: 8, padding: 12 },
  keyText: { color: '#344054', fontSize: 11, lineHeight: 16 },
  privateKeyLabel: { color: '#344054', fontSize: 9, lineHeight: 13 },
  keyActionRow: { flexDirection: 'row', gap: 10 },
  keyActionButton: {
    alignItems: 'center',
    backgroundColor: '#E7F4EF',
    borderColor: '#93D3BA',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 10,
  },
  keyActionText: { color: '#00684F', flexShrink: 1, fontSize: 13, fontWeight: '800', textAlign: 'center' },
  qrBox: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, gap: 10, padding: 12 },
  qrCanvas: { backgroundColor: '#FFFFFF' },
  qrLoadingBox: { alignItems: 'center', backgroundColor: '#FFFFFF', gap: 12, height: qrSize, justifyContent: 'center', paddingHorizontal: 20, width: qrSize },
  progressTrack: { backgroundColor: '#EAECF0', borderRadius: 999, height: 8, overflow: 'hidden', width: '100%' },
  progressFill: { backgroundColor: '#00684F', borderRadius: 999, height: '100%' },
  scannerBox: { backgroundColor: '#101828', borderRadius: 8, minHeight: 260, overflow: 'hidden' },
  camera: { flex: 1, minHeight: 260 },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 24, 40, 0.42)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    padding: 20,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  modalCard: { backgroundColor: '#FFFFFF', borderRadius: 8, gap: 12, maxWidth: 420, padding: 16, width: '100%' },
  modalTitle: { color: '#101828', fontSize: 18, fontWeight: '800' },
  modalText: { color: '#475467', fontSize: 14, lineHeight: 20 },
  modalActions: { flexDirection: 'row', gap: 10 },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 50,
  },
  cancelButtonText: { color: '#344054', fontSize: 15, fontWeight: '800' },
});
