import { StyleSheet } from 'react-native';

export const baseStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F7FB',
  },
  container: {
    padding: 20,
    paddingBottom: 36,
  },
  header: {
    marginBottom: 20,
  },
  kicker: {
    color: '#B54708',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  title: {
    color: '#101828',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  subtitle: {
    color: '#667085',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  refreshButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#004B3A',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    minHeight: 44,
    paddingHorizontal: 14,
  },
  refreshText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  advancedToggle: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    minHeight: 58,
    paddingHorizontal: 14,
  },
  advancedTitle: {
    color: '#101828',
    fontSize: 16,
    fontWeight: '800',
  },
  advancedMeta: {
    color: '#667085',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  headerTextBlock: { flex: 1, paddingRight: 10 },
  chevronIcon: { flexShrink: 0, textAlign: 'center', width: 28 },
  success: {
    color: '#047857',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 10,
  },
  error: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    marginBottom: 10,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 112,
    padding: 14,
    width: '48%',
  },
  summaryValue: {
    color: '#101828',
    fontSize: 26,
    fontWeight: '800',
    marginTop: 12,
  },
  summaryLabel: {
    color: '#667085',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 3,
    textTransform: 'uppercase',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#101828',
    fontSize: 20,
    fontWeight: '800',
  },
  sectionCount: {
    color: '#00684F',
    fontSize: 15,
    fontWeight: '800',
  },
  linkText: {
    color: '#00684F',
    fontSize: 14,
    fontWeight: '800',
  },
  form: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 22,
    padding: 14,
  },
  input: {
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    color: '#101828',
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  comboBox: {
    position: 'relative',
    zIndex: 1,
  },
  comboBoxOpen: {
    elevation: 12,
    zIndex: 1000,
  },
  comboButton: {
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  comboLabel: {
    color: '#101828',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  comboMenu: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 12,
    marginTop: 6,
    overflow: 'hidden',
    zIndex: 1001,
  },
  comboOption: {
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  comboOptionActive: {
    backgroundColor: '#E7F4EF',
  },
  comboOptionText: {
    color: '#475467',
    fontSize: 14,
    fontWeight: '800',
  },
  comboOptionTextActive: {
    color: '#00684F',
  },
  roleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  roleButton: {
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 42,
  },
  roleButtonActive: {
    backgroundColor: '#004B3A',
    borderColor: '#004B3A',
  },
  roleText: {
    color: '#475467',
    fontSize: 13,
    fontWeight: '800',
  },
  roleTextActive: {
    color: '#FFFFFF',
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#00684F',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  userList: {
    gap: 10,
    marginBottom: 24,
  },
  userCard: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  userIcon: {
    alignItems: 'center',
    backgroundColor: '#FFF7ED',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  userContent: {
    flex: 1,
  },
  userName: {
    color: '#101828',
    fontSize: 16,
    fontWeight: '800',
  },
  userMeta: {
    color: '#667085',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  userRole: {
    color: '#B54708',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 5,
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: '#E7F4EF',
    borderColor: '#D1E0FF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  smallButtonText: {
    color: '#00684F',
    fontSize: 13,
    fontWeight: '800',
  },
  dangerSmallButton: {
    backgroundColor: '#FEF3F2',
    borderColor: '#FECDCA',
  },
  dangerSmallButtonText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
  },
  requestCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  payloadText: {
    color: '#475467',
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
  },
  approveButton: {
    alignItems: 'center',
    backgroundColor: '#ECFDF3',
    borderColor: '#ABEFC6',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  approveText: {
    color: '#047857',
    fontSize: 13,
    fontWeight: '800',
  },
  rejectButton: {
    alignItems: 'center',
    backgroundColor: '#FEF3F2',
    borderColor: '#FECDCA',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  rejectText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
  },
  locked: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  lockedTitle: {
    color: '#101828',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 14,
    textAlign: 'center',
  },
  lockedText: {
    color: '#667085',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    textAlign: 'center',
  },
});
