import { StyleSheet } from 'react-native';

export const modulePalette = {
  background: '#F5F7FB',
  border: '#E4E7EC',
  borderMuted: '#EAECF0',
  borderStrong: '#D0D5DD',
  danger: '#B42318',
  dangerBorder: '#FECDCA',
  dangerSoft: '#FEF3F2',
  highlight: '#F0FDF4',
  info: '#1D4ED8',
  muted: '#667085',
  mutedStrong: '#475467',
  mutedSubtle: '#98A2B3',
  pending: '#D92D20',
  primary: '#00684F',
  primaryBorder: '#93D3BA',
  primarySoft: '#E7F4EF',
  secondary: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceMuted: '#F9FAFB',
  success: '#047857',
  text: '#101828',
  warning: '#B54708',
} as const;

export const moduleMetrics = {
  avatarSize: 44,
  buttonHeight: 48,
  cardPadding: 14,
  chipHeight: 40,
  comboHeight: 46,
  containerBottomPadding: 36,
  containerPadding: 20,
  dateChipHeight: 58,
  fieldHeight: 46,
  iconButtonSize: 40,
  radius: 8,
  sectionGap: 12,
  smallIconButtonSize: 34,
  secondaryButtonHeight: 44,
} as const;

const shellStyles = {
  safeArea: { flex: 1, backgroundColor: modulePalette.background },
  container: { padding: moduleMetrics.containerPadding, paddingBottom: moduleMetrics.containerBottomPadding },
  header: { marginBottom: 20 },
  kicker: { color: modulePalette.primary, fontSize: 14, fontWeight: '800', marginBottom: 6, textTransform: 'uppercase' },
  title: { color: modulePalette.text, fontSize: 28, fontWeight: '800', lineHeight: 34 },
  subtitle: { color: modulePalette.muted, fontSize: 15, lineHeight: 22, marginTop: 8 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  sectionTitle: { color: modulePalette.text, fontSize: 20, fontWeight: '800' },
  sectionCount: { color: modulePalette.primary, fontSize: 16, fontWeight: '800' },
  empty: { color: modulePalette.muted, fontSize: 14, lineHeight: 20 },
  error: { color: modulePalette.danger, fontSize: 13, fontWeight: '700', lineHeight: 19 },
  success: { color: modulePalette.success, fontSize: 13, fontWeight: '800' },
  headerTextBlock: { flex: 1, paddingRight: 10 },
  chevronIcon: { flexShrink: 0, textAlign: 'center', width: 28 },
  chevronIconSmall: { flexShrink: 0, textAlign: 'center', width: 22 },
  panelHint: { color: modulePalette.muted, fontSize: 13, lineHeight: 19, marginTop: 3, paddingRight: 8 },
  addTitle: { color: modulePalette.text, fontSize: 17, fontWeight: '800' },
  addHint: { color: modulePalette.muted, fontSize: 13, lineHeight: 19, marginTop: 3, paddingRight: 8 },
} as const;

const surfaceStyles = {
  card: { backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1 },
  form: { backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, gap: 10, padding: moduleMetrics.cardPadding },
  addHeader: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: moduleMetrics.cardPadding },
  searchBox: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 10, marginBottom: 14, paddingHorizontal: 14 },
  segmentedControl: { backgroundColor: modulePalette.border, borderRadius: moduleMetrics.radius, flexDirection: 'row', gap: 4, marginBottom: 14, padding: 4 },
} as const;

const controlStyles = {
  input: { backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, color: modulePalette.text, fontSize: 15, minHeight: moduleMetrics.fieldHeight, paddingHorizontal: 12, paddingVertical: 10 },
  textArea: { minHeight: 86, textAlignVertical: 'top' },
  searchInput: { color: modulePalette.text, flex: 1, fontSize: 15, minHeight: moduleMetrics.fieldHeight },
  button: { alignItems: 'center', backgroundColor: modulePalette.primary, borderRadius: moduleMetrics.radius, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: moduleMetrics.buttonHeight },
  buttonDisabled: { opacity: 0.7 },
  disabled: { opacity: 0.7 },
  buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  secondaryButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primaryBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: moduleMetrics.secondaryButtonHeight },
  secondaryButtonText: { color: modulePalette.primary, fontSize: 14, fontWeight: '800' },
  segmentButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primaryBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 44, paddingHorizontal: 12 },
  segmentButtonActive: { backgroundColor: modulePalette.primary, borderColor: modulePalette.primary },
  segmentButtonText: { color: modulePalette.primary, flexShrink: 1, fontSize: 14, fontWeight: '800', textAlign: 'center' },
  segmentButtonTextActive: { color: '#FFFFFF' },
  comboBox: { flex: 1, position: 'relative', zIndex: 1 },
  comboBoxOpen: { elevation: 12, zIndex: 1000 },
  comboTitle: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '800', marginBottom: 6 },
  comboButton: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: moduleMetrics.comboHeight, paddingHorizontal: 12 },
  comboLabel: { color: modulePalette.text, flex: 1, fontSize: 14, fontWeight: '800' },
  comboMenu: { backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, elevation: 12, marginTop: 6, maxHeight: 220, overflow: 'hidden', zIndex: 1001 },
  comboMenuScroll: { maxHeight: 220 },
  comboOption: { justifyContent: 'center', minHeight: 44, paddingHorizontal: 12 },
  comboOptionActive: { backgroundColor: modulePalette.highlight },
  comboOptionText: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '700' },
  comboOptionTextActive: { color: modulePalette.primary },
  dateField: { alignItems: 'center', backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 9, minHeight: moduleMetrics.fieldHeight, paddingHorizontal: 12 },
  dateFieldText: { color: modulePalette.text, flex: 1, fontSize: 14, fontWeight: '800' },
  datePicker: { backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, gap: 10, marginTop: 8, padding: 10 },
  datePickerHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  datePickerTitle: { color: modulePalette.text, fontSize: 14, fontWeight: '800' },
  dateGrid: { flexDirection: 'row', gap: 6 },
  dateChip: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, minHeight: moduleMetrics.dateChipHeight, justifyContent: 'center' },
  dateChipActive: { backgroundColor: modulePalette.primary, borderColor: modulePalette.primary },
  dateChipDay: { color: modulePalette.mutedStrong, fontSize: 11, fontWeight: '800' },
  dateChipDate: { color: modulePalette.text, fontSize: 11, fontWeight: '800', marginTop: 3 },
  dateChipTextActive: { color: '#FFFFFF' },
  smallIconButton: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, height: moduleMetrics.smallIconButtonSize, justifyContent: 'center', width: moduleMetrics.smallIconButtonSize },
  navButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderRadius: moduleMetrics.radius, height: 44, justifyContent: 'center', width: 44 },
  iconButton: { alignItems: 'center', backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.borderMuted, borderRadius: moduleMetrics.radius, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  toggleRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  toggleButton: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', minWidth: '47%', minHeight: 44 },
  toggleButtonActive: { backgroundColor: modulePalette.primary, borderColor: modulePalette.primary },
  toggleText: { color: modulePalette.mutedStrong, fontSize: 14, fontWeight: '800' },
  toggleTextActive: { color: '#FFFFFF' },
  refreshButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primaryBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 5, minHeight: 40, paddingHorizontal: 10 },
  timeRow: { flexDirection: 'row', gap: 10 },
} as const;

const statusStyles = {
  syncDot: { borderRadius: 5, height: 10, marginTop: 5, width: 10 },
  syncDotDone: { backgroundColor: '#12B76A' },
  syncDotPending: { backgroundColor: modulePalette.pending },
  personalBadge: { color: modulePalette.primary, fontSize: 11, fontWeight: '800' },
  visitedBadge: { color: modulePalette.primary, fontSize: 11, fontWeight: '800' },
  inactiveBadge: { color: modulePalette.muted, fontSize: 11, fontWeight: '800' },
  requestStatus: { color: modulePalette.muted, fontSize: 12, fontWeight: '800' },
  requestStatusPending: { color: modulePalette.warning },
  noteCategory: { color: modulePalette.primary, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  noteBadge: { color: modulePalette.success, fontSize: 12, fontWeight: '800' },
} as const;

const dataStyles = {
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  contactContent: { flex: 1 },
  contactName: { color: modulePalette.text, flex: 1, fontSize: 17, fontWeight: '800' },
  contactRole: { color: modulePalette.mutedStrong, fontSize: 14, fontWeight: '700', marginTop: 3 },
  contactDetail: { color: modulePalette.muted, fontSize: 13, lineHeight: 19, marginTop: 5 },
  avatar: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderRadius: moduleMetrics.radius, height: moduleMetrics.avatarSize, justifyContent: 'center', width: moduleMetrics.avatarSize },
  avatarText: { color: modulePalette.primary, fontSize: 14, fontWeight: '800' },
  hfuAvatar: { alignItems: 'center', backgroundColor: modulePalette.highlight, borderRadius: moduleMetrics.radius, height: moduleMetrics.avatarSize, justifyContent: 'center', width: moduleMetrics.avatarSize },
  hfuAvatarText: { color: modulePalette.primary, fontSize: 14, fontWeight: '800' },
  filterPanel: { gap: 12, marginBottom: 14 },
  filterGroup: { gap: 8 },
  filterGroupTitle: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '800' },
  filterChips: { flexDirection: 'row', gap: 8, paddingRight: 20 },
  filterChip: { backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, justifyContent: 'center', minHeight: moduleMetrics.chipHeight, paddingHorizontal: 12 },
  filterChipActive: { backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primary },
  filterChipText: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '700' },
  filterChipTextActive: { color: modulePalette.primary },
  itemList: { gap: 10, marginBottom: 16 },
  itemCard: { backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, padding: 12 },
  itemCardActive: { borderColor: modulePalette.primary, borderWidth: 2 },
  itemTitle: { color: modulePalette.text, fontSize: 15, fontWeight: '800' },
  itemMeta: { color: modulePalette.muted, fontSize: 13, lineHeight: 19, marginTop: 4 },
} as const;

const scheduleStyles = {
  importSection: { marginTop: 18, zIndex: 1 },
  importPanel: { ...surfaceStyles.card, gap: 10, padding: 14, zIndex: 1 },
  importButton: { alignItems: 'center', backgroundColor: modulePalette.primary, borderRadius: moduleMetrics.radius, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 48 },
  importButtonDisabled: { backgroundColor: modulePalette.mutedSubtle },
  importButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  importModeRow: { backgroundColor: modulePalette.borderMuted, borderRadius: moduleMetrics.radius, flexDirection: 'row', gap: 6, padding: 4 },
  importModeButton: { alignItems: 'center', borderRadius: moduleMetrics.radius - 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 44, paddingHorizontal: 8 },
  importModeButtonActive: { backgroundColor: modulePalette.primary },
  importModeText: { color: modulePalette.mutedStrong, flexShrink: 1, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  importModeTextActive: { color: '#FFFFFF' },
  courseImportList: { gap: 8 },
  courseImportHeader: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  refreshCoursesButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primaryBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 5, minHeight: 40, paddingHorizontal: 10 },
  refreshCoursesText: { color: modulePalette.primary, fontSize: 12, fontWeight: '800' },
  courseImportCard: { ...surfaceStyles.card, alignItems: 'center', flexDirection: 'row', gap: 10, padding: 10 },
  courseImportText: { flex: 1 },
  courseImportTitle: { color: modulePalette.text, fontSize: 14, fontWeight: '800', lineHeight: 20 },
  courseImportMeta: { color: modulePalette.muted, fontSize: 12, fontWeight: '700', marginTop: 2 },
  courseImportButton: { alignItems: 'center', backgroundColor: modulePalette.primary, borderRadius: moduleMetrics.radius, height: 44, justifyContent: 'center', width: 44 },
  todayCard: { ...surfaceStyles.card, gap: 14, marginBottom: 14, padding: 14 },
  todayCardActive: {},
  statsBar: { alignItems: 'stretch', backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', marginBottom: 14, overflow: 'hidden' },
  statItem: { flex: 1, gap: 2, justifyContent: 'center', minHeight: 72, paddingHorizontal: 12, paddingVertical: 10 },
  statDivider: { backgroundColor: modulePalette.borderMuted, width: 1 },
  statValue: { color: modulePalette.primary, fontSize: 21, fontWeight: '800', textAlign: 'center' },
  statLabel: { color: modulePalette.muted, fontSize: 12, fontWeight: '800', lineHeight: 17, textAlign: 'center', textTransform: 'uppercase' },
  dayNav: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  dayNavTitleBlock: { alignItems: 'center', flex: 1 },
  todayHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  todayKicker: { color: modulePalette.primary, fontSize: 13, fontWeight: '800', textTransform: 'uppercase' },
  todayKickerCurrent: { color: modulePalette.primary },
  todayTitle: { color: modulePalette.text, fontSize: 20, fontWeight: '800', marginTop: 4 },
  todayCount: { backgroundColor: modulePalette.primary, borderRadius: moduleMetrics.radius, color: '#FFFFFF', fontSize: 16, fontWeight: '800', minWidth: 34, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6, textAlign: 'center' },
  todaySection: { gap: 8 },
  todaySectionTitle: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '800', textTransform: 'uppercase' },
  todayLessonCard: { ...surfaceStyles.card, padding: 10, position: 'relative' },
  editableLessonCard: { borderColor: modulePalette.primaryBorder },
  inactiveLessonCard: { opacity: 0.68 },
  inactiveLessonText: { color: modulePalette.muted },
  todayMealCard: { gap: 5 },
  mealItemDivider: { borderTopColor: modulePalette.borderMuted, borderTopWidth: 1, marginTop: 10, paddingTop: 10 },
  mealItemHeader: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  mealLabel: { color: modulePalette.mutedStrong, flex: 1, fontSize: 12, fontWeight: '800' },
  mealPrice: { color: modulePalette.warning, flexShrink: 0, fontSize: 12, fontWeight: '800' },
  mealTitle: { color: modulePalette.text, fontSize: 14, fontWeight: '800', lineHeight: 20 },
  mealAlt: { color: modulePalette.mutedStrong, fontSize: 13, lineHeight: 18 },
  weekPanel: { marginBottom: 18, zIndex: 20 },
  weekContent: { ...surfaceStyles.card, padding: 12 },
  weekNav: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  weekTitle: { color: modulePalette.text, fontSize: 18, fontWeight: '800' },
  descriptionInput: { minHeight: 88, paddingTop: 12, textAlignVertical: 'top' },
  lessonCard: { ...surfaceStyles.card, marginTop: 8, padding: 10 },
  lessonTime: { color: modulePalette.primary, fontSize: 12, fontWeight: '800' },
  lessonHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between', marginTop: 5 },
  lessonTitle: { color: modulePalette.text, flex: 1, fontSize: 15, fontWeight: '800', paddingRight: 24 },
  lessonBadges: { alignItems: 'flex-end', gap: 4 },
  lessonMeta: { color: modulePalette.muted, fontSize: 12, lineHeight: 18, marginTop: 4 },
  lessonDescription: { color: modulePalette.mutedStrong, fontSize: 12, lineHeight: 18, marginTop: 6 },
  lessonActions: { flexDirection: 'row', gap: 8, marginTop: 10 },
  lessonStatusButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primaryBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 44, paddingHorizontal: 8 },
  lessonStatusButtonActive: { backgroundColor: modulePalette.primary, borderColor: modulePalette.primary },
  lessonStatusButtonText: { color: modulePalette.primary, flexShrink: 1, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  lessonStatusButtonTextActive: { color: '#FFFFFF' },
  lessonModuleButton: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 44, paddingHorizontal: 8 },
  lessonModuleButtonText: { color: modulePalette.primary, flexShrink: 1, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  lessonEditButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primaryBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 44 },
  lessonEditButtonText: { color: modulePalette.primary, fontSize: 13, fontWeight: '800' },
  lessonDeleteButton: { alignItems: 'center', backgroundColor: modulePalette.dangerSoft, borderColor: modulePalette.dangerBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 44 },
  lessonDeleteButtonText: { color: modulePalette.danger, fontSize: 13, fontWeight: '800' },
  lessonRemoveIconButton: { alignItems: 'center', backgroundColor: modulePalette.dangerSoft, borderColor: modulePalette.dangerBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, height: 34, justifyContent: 'center', position: 'absolute', right: 8, top: 8, width: 34, zIndex: 2 },
  editPanel: { marginBottom: 18, zIndex: 40 },
  editHeader: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 14 },
  editActions: { flexDirection: 'row', gap: 10 },
  cancelButton: { alignItems: 'center', backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 48 },
  cancelButtonText: { color: modulePalette.mutedStrong, fontSize: 14, fontWeight: '800' },
  personalPanel: { marginTop: 4, zIndex: 30 },
  personalHeader: { alignItems: 'center', backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 14 },
  requestsPanel: { marginTop: 18, zIndex: 10 },
  requestsContent: { backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, gap: 10, padding: 12 },
  panelHeaderActions: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  requestList: { gap: 12 },
  requestCard: { ...surfaceStyles.card, padding: 14 },
  requestCardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  requestTitle: { color: modulePalette.text, flex: 1, fontSize: 16, fontWeight: '800' },
  requestMeta: { color: modulePalette.muted, fontSize: 13, lineHeight: 19, marginTop: 5 },
  requestDescription: { color: modulePalette.mutedStrong, fontSize: 13, lineHeight: 19, marginTop: 8 },
  requestActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  acceptButton: { alignItems: 'center', backgroundColor: modulePalette.success, borderRadius: moduleMetrics.radius, flex: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: 44 },
  rejectButton: { alignItems: 'center', backgroundColor: modulePalette.danger, borderRadius: moduleMetrics.radius, flex: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: 44 },
  requestActionText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  modalOverlay: { alignItems: 'center', backgroundColor: 'rgba(16, 24, 40, 0.45)', flex: 1, justifyContent: 'center', padding: 20 },
  modalCard: { backgroundColor: modulePalette.surface, borderRadius: moduleMetrics.radius, gap: 12, maxWidth: 420, padding: 18, width: '100%' },
  modalTitle: { color: modulePalette.text, fontSize: 19, fontWeight: '800' },
  modalText: { color: modulePalette.mutedStrong, fontSize: 14, lineHeight: 20 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 4 },
  modalCancelButton: { alignItems: 'center', backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 46 },
  modalConfirmButton: { alignItems: 'center', backgroundColor: modulePalette.primary, borderRadius: moduleMetrics.radius, flex: 1, justifyContent: 'center', minHeight: 46 },
  modalDangerButton: { backgroundColor: modulePalette.danger },
  modalConfirmText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  inviteBox: { gap: 8 },
  accountResult: { alignItems: 'center', backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.borderMuted, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 10, padding: 10 },
  accountTextBlock: { flex: 1 },
  accountName: { color: modulePalette.text, fontSize: 14, fontWeight: '800' },
  accountEmail: { color: modulePalette.muted, fontSize: 12, marginTop: 2 },
  inviteeList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  inviteeChip: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primaryBorder, borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 5, paddingHorizontal: 10, paddingVertical: 7 },
  inviteeChipText: { color: modulePalette.primary, fontSize: 12, fontWeight: '800' },
} as const;

const deadlinesStyles = {
  kicker: { ...shellStyles.kicker, color: modulePalette.primary },
  todoList: { gap: 10 },
  todoCard: { ...surfaceStyles.card, padding: 14 },
  todoTopRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  checkbox: { alignItems: 'center', backgroundColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, height: 40, justifyContent: 'center', width: 40 },
  disabledAction: { opacity: 0.5 },
  todoTitleBlock: { flex: 1 },
  todoTitle: { color: modulePalette.text, fontSize: 16, fontWeight: '800' },
  todoMeta: { color: modulePalette.muted, fontSize: 12, lineHeight: 18, marginTop: 3 },
  expandButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  todoDetails: { borderTopColor: modulePalette.borderMuted, borderTopWidth: 1, gap: 8, marginTop: 12, paddingTop: 12 },
  todoDescription: { color: modulePalette.mutedStrong, fontSize: 13, lineHeight: 19 },
  subtaskRow: { alignItems: 'center', flexDirection: 'row', gap: 9, minHeight: 34 },
  subtaskCheckbox: { alignItems: 'center', borderColor: modulePalette.borderStrong, borderRadius: 7, borderWidth: 1, height: 24, justifyContent: 'center', width: 24 },
  subtaskCheckboxDone: { backgroundColor: modulePalette.success, borderColor: modulePalette.success },
  subtaskText: { color: modulePalette.mutedStrong, flex: 1, fontSize: 14, fontWeight: '700' },
  subtaskTextDone: { color: modulePalette.mutedSubtle, textDecorationLine: 'line-through' },
  historySection: { marginTop: 24 },
  historyCard: { ...surfaceStyles.card, padding: 14 },
  historySubtasks: { gap: 4, marginTop: 10 },
  historySubtask: { color: modulePalette.muted, fontSize: 12, lineHeight: 18 },
  notesPanel: { marginBottom: 18 },
  notesContent: { ...surfaceStyles.card, gap: 10, padding: 12 },
  noteCard: { backgroundColor: modulePalette.surfaceMuted, borderColor: modulePalette.borderMuted, borderRadius: moduleMetrics.radius, borderWidth: 1, padding: 12 },
  noteCardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  noteCategory: { color: modulePalette.primary, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  noteBadge: { color: modulePalette.success, fontSize: 12, fontWeight: '800' },
  noteTitle: { color: modulePalette.text, fontSize: 16, fontWeight: '800', marginTop: 7 },
  noteText: { color: modulePalette.mutedStrong, fontSize: 14, lineHeight: 20, marginTop: 5 },
  addPanel: { marginTop: 18 },
  fieldLabel: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '800' },
  subtaskInputRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  subtaskInput: { flex: 1 },
  removeButton: { alignItems: 'center', backgroundColor: modulePalette.dangerSoft, borderColor: modulePalette.dangerBorder, borderRadius: moduleMetrics.radius, borderWidth: 1, height: 46, justifyContent: 'center', width: 46 },
  removeButtonDisabled: { opacity: 0.4 },
} as const;

const contactsStyles = {
  kicker: { ...shellStyles.kicker, color: modulePalette.primary },
  sectionSubtitle: { color: modulePalette.muted, fontSize: 15, lineHeight: 22, marginTop: 5 },
  contactList: { gap: 12, marginBottom: 18 },
  contactCard: { ...surfaceStyles.card, alignItems: 'flex-start', flexDirection: 'row', gap: 12, padding: 14 },
  avatar: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderRadius: moduleMetrics.radius, height: moduleMetrics.avatarSize, justifyContent: 'center', width: moduleMetrics.avatarSize },
  avatarText: { color: modulePalette.primary, fontSize: 14, fontWeight: '800' },
  hfuAvatar: { alignItems: 'center', backgroundColor: modulePalette.highlight, borderRadius: moduleMetrics.radius, height: moduleMetrics.avatarSize, justifyContent: 'center', width: moduleMetrics.avatarSize },
  hfuAvatarText: { color: modulePalette.primary, fontSize: 14, fontWeight: '800' },
  contactContent: { flex: 1 },
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  contactName: { color: modulePalette.text, flex: 1, fontSize: 17, fontWeight: '800' },
  contactRole: { color: modulePalette.mutedStrong, fontSize: 14, fontWeight: '700', marginTop: 3 },
  contactDetail: { color: modulePalette.muted, fontSize: 13, lineHeight: 19, marginTop: 5 },
  addPanel: { marginTop: 4 },
  hfuHeader: { marginBottom: 14 },
  sectionTitle: { color: modulePalette.text, fontSize: 20, fontWeight: '800', lineHeight: 28 },
  filterPanel: { gap: 12, marginBottom: 14 },
  filterGroup: { gap: 8 },
  filterGroupTitle: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '800' },
  filterChips: { flexDirection: 'row', gap: 8, paddingRight: 20 },
  filterChip: { backgroundColor: modulePalette.surface, borderColor: modulePalette.borderStrong, borderRadius: moduleMetrics.radius, borderWidth: 1, justifyContent: 'center', minHeight: moduleMetrics.chipHeight, paddingHorizontal: 12 },
  filterChipActive: { backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primary },
  filterChipText: { color: modulePalette.mutedStrong, fontSize: 13, fontWeight: '700' },
  filterChipTextActive: { color: modulePalette.primary },
  hfuDetails: { borderTopColor: modulePalette.border, borderTopWidth: 1, marginTop: 10, paddingTop: 8 },
  linkButton: { alignItems: 'center', flexDirection: 'row', gap: 6, marginTop: 8, minHeight: 34 },
  linkButtonText: { color: modulePalette.primary, fontSize: 13, fontWeight: '800' },
  loadMoreButton: { alignItems: 'center', backgroundColor: modulePalette.primarySoft, borderColor: modulePalette.primary, borderRadius: moduleMetrics.radius, borderWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 46, paddingHorizontal: 14 },
  loadMoreButtonDisabled: { opacity: 0.55 },
  loadMoreButtonText: { color: modulePalette.primary, fontSize: 14, fontWeight: '800' },
} as const;

const managerStyles = {
  kicker: { ...shellStyles.kicker, color: modulePalette.primary },
  toggleRow: { ...surfaceStyles.segmentedControl, marginBottom: 12 },
  toggleButton: { ...controlStyles.segmentButton, flex: 1, minWidth: '47%' },
  toggleButtonActive: { backgroundColor: modulePalette.primary, borderColor: modulePalette.primary },
  toggleText: { color: modulePalette.mutedStrong, fontSize: 14, fontWeight: '800' },
  toggleTextActive: { color: '#FFFFFF' },
  itemList: { gap: 10, marginBottom: 16 },
  itemCard: { ...surfaceStyles.card, padding: 12 },
  itemCardActive: { borderColor: modulePalette.primary, borderWidth: 2 },
  itemTitle: { color: modulePalette.text, fontSize: 15, fontWeight: '800' },
  itemMeta: { color: modulePalette.muted, fontSize: 13, lineHeight: 19, marginTop: 4 },
  helperText: { color: modulePalette.muted, fontSize: 14, lineHeight: 20, marginBottom: 16 },
  deleteBox: { ...surfaceStyles.card, gap: 10, marginBottom: 22, padding: 14 },
  timeRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 10 },
  flexInput: { flex: 1 },
  textArea: { minHeight: 86, textAlignVertical: 'top' },
  requestCard: { backgroundColor: modulePalette.surface, borderColor: modulePalette.border, borderRadius: moduleMetrics.radius, borderWidth: 1, padding: 12 },
  locked: { alignItems: 'center', flex: 1, justifyContent: 'center', padding: 24 },
  embeddedLocked: { ...surfaceStyles.card, alignItems: 'center', gap: 10, marginBottom: 18, padding: 18 },
  lockedTitle: { color: modulePalette.text, fontSize: 22, fontWeight: '800', marginTop: 14, textAlign: 'center' },
  lockedText: { color: modulePalette.muted, fontSize: 15, lineHeight: 22, marginTop: 8, textAlign: 'center' },
} as const;

export const scheduleBaseStyles = StyleSheet.create({
  ...shellStyles,
  ...surfaceStyles,
  ...controlStyles,
  ...statusStyles,
  ...dataStyles,
  ...scheduleStyles,
});

export const deadlinesBaseStyles = StyleSheet.create({
  ...shellStyles,
  ...surfaceStyles,
  ...controlStyles,
  ...statusStyles,
  ...dataStyles,
  ...deadlinesStyles,
});

export const contactsBaseStyles = StyleSheet.create({
  ...shellStyles,
  ...surfaceStyles,
  ...controlStyles,
  ...statusStyles,
  ...dataStyles,
  ...contactsStyles,
});

export const managerBaseStyles = StyleSheet.create({
  ...shellStyles,
  ...surfaceStyles,
  ...controlStyles,
  ...statusStyles,
  ...dataStyles,
  ...managerStyles,
});
