import { StyleSheet } from 'react-native';

export const baseStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F5F7FB' },
  container: { padding: 20, paddingBottom: 36 },
  header: { marginBottom: 20 },
  kicker: { color: '#00684F', fontSize: 14, fontWeight: '800', marginBottom: 6, textTransform: 'uppercase' },
  title: { color: '#101828', fontSize: 28, fontWeight: '800', lineHeight: 34 },
  subtitle: { color: '#667085', fontSize: 15, lineHeight: 22, marginBottom: 14, marginTop: 8 },
  importSection: { marginTop: 18, zIndex: 1 },
  importPanel: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, gap: 10, padding: 14, zIndex: 1 },
  importModeRow: { backgroundColor: '#EAECF0', borderRadius: 8, flexDirection: 'row', gap: 6, padding: 4 },
  importModeButton: { alignItems: 'center', borderRadius: 7, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 42, paddingHorizontal: 8 },
  importModeButtonActive: { backgroundColor: '#00684F' },
  importModeText: { color: '#475467', flexShrink: 1, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  importModeTextActive: { color: '#FFFFFF' },
  comboBox: { flex: 1, position: 'relative', zIndex: 1 },
  comboBoxOpen: { elevation: 12, zIndex: 1000 },
  comboTitle: { color: '#344054', fontSize: 13, fontWeight: '800', marginBottom: 6 },
  comboButton: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 46, paddingHorizontal: 12 },
  comboLabel: { color: '#101828', flex: 1, fontSize: 14, fontWeight: '800' },
  chevronIcon: { flexShrink: 0, textAlign: 'center', width: 28 },
  comboMenu: { backgroundColor: '#FFFFFF', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, elevation: 12, marginTop: 6, maxHeight: 220, overflow: 'hidden', zIndex: 1001 },
  comboMenuScroll: { maxHeight: 220 },
  comboOption: { justifyContent: 'center', minHeight: 42, paddingHorizontal: 12 },
  comboOptionText: { color: '#475467', fontSize: 13, fontWeight: '700' },
  disabled: { opacity: 0.55 },
  importButton: { alignItems: 'center', backgroundColor: '#00684F', borderRadius: 8, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 48 },
  importButtonDisabled: { backgroundColor: '#98A2B3' },
  importButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  courseImportList: { gap: 8 },
  courseImportHeader: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  refreshCoursesButton: { alignItems: 'center', backgroundColor: '#E7F4EF', borderColor: '#93D3BA', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 5, minHeight: 36, paddingHorizontal: 10 },
  refreshCoursesText: { color: '#00684F', fontSize: 12, fontWeight: '800' },
  courseImportCard: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#EAECF0', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 10, padding: 10 },
  courseImportText: { flex: 1 },
  courseImportTitle: { color: '#101828', fontSize: 14, fontWeight: '800', lineHeight: 20 },
  courseImportMeta: { color: '#667085', fontSize: 12, fontWeight: '700', marginTop: 2 },
  courseImportButton: { alignItems: 'center', backgroundColor: '#00684F', borderRadius: 8, height: 38, justifyContent: 'center', width: 42 },
  todayCard: { backgroundColor: '#FFFFFF', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, gap: 14, marginBottom: 14, padding: 14 },
  todayCardActive: {},
  statsBar: { alignItems: 'stretch', backgroundColor: '#FFFFFF', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, flexDirection: 'row', marginBottom: 14, overflow: 'hidden' },
  statItem: { flex: 1, gap: 2, justifyContent: 'center', minHeight: 72, paddingHorizontal: 12, paddingVertical: 10 },
  statDivider: { backgroundColor: '#EAECF0', width: 1 },
  statValue: { color: '#00684F', fontSize: 21, fontWeight: '800', textAlign: 'center' },
  statLabel: { color: '#667085', fontSize: 12, fontWeight: '800', lineHeight: 17, textAlign: 'center', textTransform: 'uppercase' },
  dayNav: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  dayNavTitleBlock: { alignItems: 'center', flex: 1 },
  todayHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  todayKicker: { color: '#00684F', fontSize: 13, fontWeight: '800', textTransform: 'uppercase' },
  todayKickerCurrent: { color: '#D4A017' },
  todayTitle: { color: '#101828', fontSize: 20, fontWeight: '800', marginTop: 4 },
  todayCount: { backgroundColor: '#00684F', borderRadius: 8, color: '#FFFFFF', fontSize: 16, fontWeight: '800', minWidth: 34, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6, textAlign: 'center' },
  todaySection: { gap: 8 },
  todaySectionTitle: { color: '#344054', fontSize: 13, fontWeight: '800', textTransform: 'uppercase' },
  todayLessonCard: { backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, padding: 10 },
  editableLessonCard: { borderColor: '#93D3BA' },
  inactiveLessonCard: { opacity: 0.68 },
  inactiveLessonText: { color: '#667085' },
  todayMealCard: { gap: 5 },
  weekPanel: { marginBottom: 18, zIndex: 20 },
  weekContent: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, padding: 12 },
  weekNav: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  navButton: { alignItems: 'center', backgroundColor: '#E7F4EF', borderRadius: 8, height: 44, justifyContent: 'center', width: 44 },
  weekTitle: { color: '#101828', fontSize: 18, fontWeight: '800' },
  form: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, gap: 10, marginBottom: 22, padding: 14 },
  input: { backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, color: '#101828', fontSize: 15, minHeight: 46, paddingHorizontal: 12 },
  descriptionInput: { minHeight: 88, paddingTop: 12, textAlignVertical: 'top' },
  button: { alignItems: 'center', backgroundColor: '#00684F', borderRadius: 8, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 48 },
  buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  success: { color: '#047857', fontSize: 13, fontWeight: '800' },
  error: { color: '#B42318', fontSize: 13, fontWeight: '700' },
  weekGrid: { gap: 12, marginBottom: 18 },
  dayColumn: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, padding: 12 },
  dayColumnToday: { backgroundColor: '#F0FDF4', borderColor: '#22C55E', borderWidth: 2 },
  dayHeaderRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  dayTitle: { color: '#101828', fontSize: 18, fontWeight: '800' },
  dayTitleToday: { color: '#00684F' },
  dayDate: { color: '#667085', fontSize: 13, fontWeight: '700', marginBottom: 10, marginTop: 2 },
  todayBadge: { backgroundColor: '#00684F', borderRadius: 999, color: '#FFFFFF', fontSize: 11, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4 },
  empty: { color: '#98A2B3', fontSize: 13, lineHeight: 19 },
  mealPanel: { backgroundColor: '#ECFDF3', borderColor: '#A6F4C5', borderRadius: 8, borderWidth: 1, marginBottom: 10, overflow: 'hidden' },
  mealHeaderButton: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between', minHeight: 48, paddingHorizontal: 10, paddingVertical: 8 },
  mealHeaderText: { flex: 1 },
  mealPanelTitle: { color: '#00684F', fontSize: 13, fontWeight: '800', textTransform: 'uppercase' },
  mealPanelMeta: { color: '#475467', fontSize: 12, fontWeight: '700', marginTop: 2 },
  mealList: { backgroundColor: '#FFFFFF', borderTopColor: '#A6F4C5', borderTopWidth: 1, padding: 10 },
  mealItem: { gap: 5 },
  mealItemDivider: { borderTopColor: '#EAECF0', borderTopWidth: 1, marginTop: 10, paddingTop: 10 },
  mealItemHeader: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  mealLabel: { color: '#344054', flex: 1, fontSize: 12, fontWeight: '800' },
  mealPrice: { color: '#B54708', flexShrink: 0, fontSize: 12, fontWeight: '800' },
  mealTitle: { color: '#101828', fontSize: 14, fontWeight: '800', lineHeight: 20 },
  mealAlt: { color: '#475467', fontSize: 13, lineHeight: 18 },
  lessonCard: { backgroundColor: '#F9FAFB', borderColor: '#EAECF0', borderRadius: 8, borderWidth: 1, marginTop: 8, padding: 10 },
  lessonTime: { color: '#1D4ED8', fontSize: 12, fontWeight: '800' },
  lessonHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between', marginTop: 5 },
  lessonTitle: { color: '#101828', flex: 1, fontSize: 15, fontWeight: '800' },
  syncDot: { borderRadius: 5, height: 10, marginTop: 4, width: 10 },
  syncDotDone: { backgroundColor: '#12B76A' },
  syncDotPending: { backgroundColor: '#D92D20' },
  lessonBadges: { alignItems: 'flex-end', gap: 4 },
  personalBadge: { color: '#047857', fontSize: 11, fontWeight: '800' },
  visitedBadge: { color: '#00684F', fontSize: 11, fontWeight: '800' },
  inactiveBadge: { color: '#B54708', fontSize: 11, fontWeight: '800' },
  lessonMeta: { color: '#667085', fontSize: 12, lineHeight: 18, marginTop: 4 },
  lessonDescription: { color: '#475467', fontSize: 12, lineHeight: 18, marginTop: 6 },
  lessonActions: { flexDirection: 'row', gap: 8, marginTop: 10 },
  lessonStatusButton: { alignItems: 'center', backgroundColor: '#E7F4EF', borderColor: '#93D3BA', borderRadius: 8, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 40, paddingHorizontal: 8 },
  lessonStatusButtonActive: { backgroundColor: '#00684F', borderColor: '#00684F' },
  lessonStatusButtonText: { color: '#00684F', flexShrink: 1, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  lessonStatusButtonTextActive: { color: '#FFFFFF' },
  lessonModuleButton: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 40, paddingHorizontal: 8 },
  lessonModuleButtonText: { color: '#00684F', flexShrink: 1, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  lessonEditButton: { alignItems: 'center', backgroundColor: '#E7F4EF', borderColor: '#93D3BA', borderRadius: 8, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 40 },
  lessonEditButtonText: { color: '#00684F', fontSize: 13, fontWeight: '800' },
  lessonDeleteButton: { alignItems: 'center', backgroundColor: '#FEF3F2', borderColor: '#FECDCA', borderRadius: 8, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 40 },
  lessonDeleteButtonText: { color: '#B42318', fontSize: 13, fontWeight: '800' },
  editPanel: { marginBottom: 18, zIndex: 40 },
  editHeader: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 14 },
  iconButton: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#EAECF0', borderRadius: 8, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  editActions: { flexDirection: 'row', gap: 10 },
  cancelButton: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 48 },
  cancelButtonText: { color: '#344054', fontSize: 14, fontWeight: '800' },
  personalPanel: { marginTop: 4, zIndex: 30 },
  personalHeader: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 14 },
  headerTextBlock: { flex: 1, paddingRight: 10 },
  requestsPanel: { marginTop: 18, zIndex: 10 },
  requestsContent: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, gap: 10, padding: 12 },
  panelHeaderActions: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  sectionTitle: { color: '#101828', fontSize: 17, fontWeight: '800' },
  sectionCount: { color: '#00684F', fontSize: 17, fontWeight: '800' },
  panelHint: { color: '#667085', fontSize: 13, lineHeight: 19, marginTop: 3, paddingRight: 8 },
  requestList: { gap: 12 },
  requestCard: { backgroundColor: '#FFFFFF', borderColor: '#E4E7EC', borderRadius: 8, borderWidth: 1, padding: 14 },
  requestCardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  requestTitle: { color: '#101828', flex: 1, fontSize: 16, fontWeight: '800' },
  requestStatus: { color: '#667085', fontSize: 12, fontWeight: '800' },
  requestStatusPending: { color: '#B54708' },
  requestMeta: { color: '#667085', fontSize: 13, lineHeight: 19, marginTop: 5 },
  requestDescription: { color: '#475467', fontSize: 13, lineHeight: 19, marginTop: 8 },
  requestActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  acceptButton: { alignItems: 'center', backgroundColor: '#047857', borderRadius: 8, flex: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: 44 },
  rejectButton: { alignItems: 'center', backgroundColor: '#B42318', borderRadius: 8, flex: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: 44 },
  requestActionText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  segmentButton: { alignItems: 'center', backgroundColor: '#E7F4EF', borderColor: '#93D3BA', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 46 },
  segmentButtonActive: { backgroundColor: '#00684F', borderColor: '#00684F' },
  segmentButtonText: { color: '#00684F', fontSize: 14, fontWeight: '800' },
  segmentButtonTextActive: { color: '#FFFFFF' },
  dateField: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 9, minHeight: 46, paddingHorizontal: 12 },
  dateFieldText: { color: '#101828', flex: 1, fontSize: 14, fontWeight: '800' },
  datePicker: { backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, padding: 10 },
  datePickerHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  datePickerTitle: { color: '#101828', fontSize: 14, fontWeight: '800' },
  smallIconButton: { alignItems: 'center', backgroundColor: '#E7F4EF', borderRadius: 8, height: 34, justifyContent: 'center', width: 34 },
  dateGrid: { flexDirection: 'row', gap: 6 },
  dateChip: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#EAECF0', borderRadius: 8, borderWidth: 1, flex: 1, minHeight: 58, justifyContent: 'center' },
  dateChipActive: { backgroundColor: '#00684F', borderColor: '#00684F' },
  dateChipDay: { color: '#667085', fontSize: 11, fontWeight: '800' },
  dateChipDate: { color: '#101828', fontSize: 11, fontWeight: '800', marginTop: 3 },
  dateChipTextActive: { color: '#FFFFFF' },
  timeRow: { flexDirection: 'row', gap: 10 },
  inviteBox: { gap: 8 },
  accountResult: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#EAECF0', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 10, padding: 10 },
  accountTextBlock: { flex: 1 },
  accountName: { color: '#101828', fontSize: 14, fontWeight: '800' },
  accountEmail: { color: '#667085', fontSize: 12, marginTop: 2 },
  inviteeList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  inviteeChip: { alignItems: 'center', backgroundColor: '#ECFDF3', borderColor: '#A6F4C5', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 5, paddingHorizontal: 10, paddingVertical: 7 },
  inviteeChipText: { color: '#00684F', fontSize: 12, fontWeight: '800' },
  modalOverlay: { alignItems: 'center', backgroundColor: 'rgba(16, 24, 40, 0.45)', flex: 1, justifyContent: 'center', padding: 20 },
  modalCard: { backgroundColor: '#FFFFFF', borderRadius: 8, gap: 12, maxWidth: 420, padding: 18, width: '100%' },
  modalTitle: { color: '#101828', fontSize: 19, fontWeight: '800' },
  modalText: { color: '#475467', fontSize: 14, lineHeight: 20 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 4 },
  modalCancelButton: { alignItems: 'center', backgroundColor: '#F9FAFB', borderColor: '#D0D5DD', borderRadius: 8, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 46 },
  modalConfirmButton: { alignItems: 'center', backgroundColor: '#00684F', borderRadius: 8, flex: 1, justifyContent: 'center', minHeight: 46 },
  modalDangerButton: { backgroundColor: '#B42318' },
  modalConfirmText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
});
