import type { Dispatch, SetStateAction } from 'react';

import type { AccountStats, CourseOption, FacultyOption, ImportOptions, Invitation, Lesson, LessonForm, Meal, Option, UserOption } from './types';

type StringOption = { id: string; name: string; shortname?: string };

export type ScheduleViewModel = {
  accountQuery: string;
  accountResults: UserOption[];
  accountStats: AccountStats | null;
  academicSemester: Option | null;
  academicSemesters: Option[];
  addInvitee: (account: UserOption) => void;
  addLesson: () => Promise<void>;
  canEditLesson: (lesson: Lesson) => boolean;
  canImport: boolean;
  closeLessonDialog: () => void;
  courseOptions: CourseOption[];
  datePickerOpen: boolean;
  deletePersonalLesson: () => Promise<void>;
  editDatePickerOpen: boolean;
  editForm: LessonForm;
  editingLesson: Lesson | null;
  faculty: FacultyOption | null;
  form: LessonForm;
  formError: string;
  formMessage: string;
  importCourse: (course: CourseOption) => Promise<void>;
  importError: string;
  importMessage: string;
  importMode: 'schedule' | 'course';
  importPanelOpen: boolean;
  importSchedule: () => Promise<void>;
  invitations: Invitation[];
  invitationError: string;
  invitees: UserOption[];
  isCourseLoading: boolean;
  loadImportCourses: () => Promise<void>;
  options: ImportOptions;
  pendingLessonAction: 'update' | 'delete' | null;
  personalFormOpen: boolean;
  requestsOpen: boolean;
  respondToInvitation: (id: number, decision: 'accept' | 'reject') => Promise<void>;
  selectedDate: Date;
  selectDate: (date: Date) => void;
  selectedDay: string;
  selectedDayOption: StringOption;
  selectedEndTime: StringOption;
  selectedIsToday: boolean;
  selectedLessons: Lesson[];
  selectedMeals: Meal[];
  selectedStartTime: StringOption;
  semester: Option | null;
  setAcademicSemester: Dispatch<SetStateAction<Option | null>>;
  setAccountQuery: Dispatch<SetStateAction<string>>;
  setDatePickerOpen: Dispatch<SetStateAction<boolean>>;
  setEditDatePickerOpen: Dispatch<SetStateAction<boolean>>;
  setEditForm: Dispatch<SetStateAction<LessonForm>>;
  setEditingLesson: Dispatch<SetStateAction<Lesson | null>>;
  setFaculty: Dispatch<SetStateAction<FacultyOption | null>>;
  setForm: Dispatch<SetStateAction<LessonForm>>;
  setImportError: Dispatch<SetStateAction<string>>;
  setImportMessage: Dispatch<SetStateAction<string>>;
  setImportMode: Dispatch<SetStateAction<'schedule' | 'course'>>;
  setImportPanelOpen: Dispatch<SetStateAction<boolean>>;
  setInvitees: Dispatch<SetStateAction<UserOption[]>>;
  setPendingLessonAction: Dispatch<SetStateAction<'update' | 'delete' | null>>;
  setPersonalFormOpen: Dispatch<SetStateAction<boolean>>;
  setRequestsOpen: Dispatch<SetStateAction<boolean>>;
  setSemester: Dispatch<SetStateAction<Option | null>>;
  setSpecialization: Dispatch<SetStateAction<Option | null>>;
  specialization: Option | null;
  specializations: Option[];
  startEditingLesson: (lesson: Lesson) => void;
  toggleLessonVisit: (lesson: Lesson) => Promise<void>;
  toggleModuleActive: (lesson: Lesson) => Promise<void>;
  updatePersonalLesson: () => Promise<void>;
};
