import { StyleSheet } from 'react-native';

export const baseStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F7FB',
  },
  container: {
    padding: 20,
    paddingBottom: 36,
  },
  header: {
    marginBottom: 20,
  },
  kicker: {
    color: '#00684F',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  title: {
    color: '#101828',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  subtitle: {
    color: '#667085',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  toggleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  toggleButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minWidth: '47%',
    minHeight: 44,
  },
  toggleButtonActive: {
    backgroundColor: '#00684F',
    borderColor: '#00684F',
  },
  toggleText: {
    color: '#475467',
    fontSize: 14,
    fontWeight: '800',
  },
  toggleTextActive: {
    color: '#FFFFFF',
  },
  comboBox: {
    flex: 1,
    marginBottom: 14,
    position: 'relative',
    zIndex: 1,
  },
  comboBoxOpen: {
    elevation: 12,
    zIndex: 1000,
  },
  comboTitle: {
    color: '#344054',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  comboButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  comboLabel: {
    color: '#101828',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  chevronIcon: { flexShrink: 0, textAlign: 'center', width: 28 },
  comboMenu: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 12,
    marginTop: 6,
    maxHeight: 220,
    overflow: 'hidden',
    zIndex: 1001,
  },
  comboMenuScroll: {
    maxHeight: 220,
  },
  comboOption: {
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  comboOptionActive: {
    backgroundColor: '#ECFDF3',
  },
  comboOptionText: {
    color: '#475467',
    fontSize: 14,
    fontWeight: '800',
  },
  comboOptionTextActive: {
    color: '#00684F',
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
  },
  actionButtonActive: {
    backgroundColor: '#004B3A',
    borderColor: '#004B3A',
  },
  actionText: {
    color: '#475467',
    fontSize: 13,
    fontWeight: '800',
  },
  actionTextActive: {
    color: '#FFFFFF',
  },
  itemList: {
    gap: 10,
    marginBottom: 16,
  },
  empty: {
    color: '#667085',
    fontSize: 14,
    lineHeight: 20,
  },
  itemCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  itemCardActive: {
    borderColor: '#00684F',
    borderWidth: 2,
  },
  itemTitle: {
    color: '#101828',
    fontSize: 15,
    fontWeight: '800',
  },
  itemMeta: {
    color: '#667085',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  form: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 22,
    padding: 14,
  },
  deleteBox: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 22,
    padding: 14,
  },
  helperText: {
    color: '#667085',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  input: {
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    color: '#101828',
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  flexInput: {
    flex: 1,
  },
  textArea: {
    minHeight: 86,
    textAlignVertical: 'top',
  },
  dateField: {
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  dateFieldText: {
    color: '#101828',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  datePicker: {
    backgroundColor: '#F9FAFB',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginTop: 8,
    padding: 10,
  },
  datePickerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  datePickerTitle: {
    color: '#101828',
    fontSize: 14,
    fontWeight: '800',
  },
  dateGrid: {
    flexDirection: 'row',
    gap: 6,
  },
  dateChip: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 54,
    justifyContent: 'center',
  },
  dateChipActive: {
    backgroundColor: '#00684F',
    borderColor: '#00684F',
  },
  dateChipDay: {
    color: '#475467',
    fontSize: 12,
    fontWeight: '800',
  },
  dateChipDate: {
    color: '#101828',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },
  dateChipTextActive: {
    color: '#FFFFFF',
  },
  smallIconButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D0D5DD',
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  timeRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  segmentButton: {
    alignItems: 'center',
    backgroundColor: '#E7F4EF',
    borderColor: '#93D3BA',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  segmentButtonActive: {
    backgroundColor: '#00684F',
    borderColor: '#00684F',
  },
  segmentButtonText: {
    color: '#00684F',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  segmentButtonTextActive: {
    color: '#FFFFFF',
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#00684F',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  success: {
    color: '#047857',
    fontSize: 13,
    fontWeight: '800',
  },
  error: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#101828',
    fontSize: 20,
    fontWeight: '800',
  },
  sectionCount: {
    color: '#00684F',
    fontSize: 15,
    fontWeight: '800',
  },
  requestCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  locked: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  embeddedLocked: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 18,
    padding: 18,
  },
  lockedTitle: {
    color: '#101828',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 14,
    textAlign: 'center',
  },
  lockedText: {
    color: '#667085',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    textAlign: 'center',
  },
});
